export const fakeProfiles = [
  {
    id: "id-1",
    name: "John Doe",
    bio: "This is the bio of John Doe. He enjoys coding and exploring new technologies. This is the bio of John Doe. He enjoys coding and exploring new technologies.",
    headline: "Tech Enthusiast and Developer | John Doe",
    photo: "https://fakeimg.pl/100x100/?text=John+Doe",
    interests: ["Coding", "Reading"],
  },
  {
    id: "id-2",
    name: "Jane Smith",
    bio: "Jane loves gaming and photography, constantly seeking new adventures.",
    headline: "Gamer & Photographer | Jane Smith",
    photo: "https://fakeimg.pl/100x100/?text=Jane+Smith",
    interests: ["Gaming", "Photography", "Sports"],
  },
  {
    id: "id-3",
    name: "Emily Johnson",
    bio: "A passionate traveler with a love for photography and culture.",
    headline: "Traveler & Explorer | Emily Johnson",
    photo: "https://fakeimg.pl/100x100/?text=Emily+Johnson",
    interests: ["Traveling", "Photography"],
  },
  {
    id: "id-4",
    name: "Michael Brown",
    bio: "Michael is a coding enthusiast and an open-source contributor.",
    headline: "Developer | Michael Brown",
    photo: "https://fakeimg.pl/100x100/?text=Michael+Brown",
    interests: ["Coding", "Open Source"],
  },
  {
    id: "id-5",
    name: "Olivia Davis",
    bio: "Olivia enjoys reading books, coding, and exploring new tech.",
    headline: "Coder & Bookworm | Olivia Davis",
    photo: "https://fakeimg.pl/100x100/?text=Olivia+Davis",
    interests: ["Reading", "Coding"],
  },
  {
    id: "id-6",
    name: "James Wilson",
    bio: "An avid sports fan and tech enthusiast, always on the move.",
    headline: "Sports Enthusiast | James Wilson",
    photo: "https://fakeimg.pl/100x100/?text=James+Wilson",
    interests: ["Sports", "Tech"],
  },
  {
    id: "id-7",
    name: "Charlotte Miller",
    bio: "Creative mind with a passion for design and digital art.",
    headline: "Designer | Charlotte Miller",
    photo: "https://fakeimg.pl/100x100/?text=Charlotte+Miller",
    interests: ["Design", "Art"],
  },
  {
    id: "id-8",
    name: "William Moore",
    bio: "William loves to create digital art and experiment with new styles.",
    headline: "Artist & Creator | William Moore",
    photo: "https://fakeimg.pl/100x100/?text=William+Moore",
    interests: ["Art", "Design"],
  },
  {
    id: "id-9",
    name: "Sophia Taylor",
    bio: "A passionate coder and tech enthusiast with a love for web development.",
    headline: "Web Developer | Sophia Taylor",
    photo: "https://fakeimg.pl/100x100/?text=Sophia+Taylor",
    interests: ["Web Development", "Tech"],
  },
  {
    id: "id-10",
    name: "Daniel Harris",
    bio: "Daniel is passionate about AI, robotics, and machine learning.",
    headline: "AI Enthusiast | Daniel Harris",
    photo: "https://fakeimg.pl/100x100/?text=Daniel+Harris",
    interests: ["AI", "Robotics", "Machine Learning"],
  },
  {
    id: "id-11",
    name: "Isabella Clark",
    bio: "Isabella is a musician and sound engineer exploring the world of digital music.",
    headline: "Musician | Isabella Clark",
    photo: "https://fakeimg.pl/100x100/?text=Isabella+Clark",
    interests: ["Music", "Sound Engineering"],
  },
  {
    id: "id-12",
    name: "Ethan Lewis",
    bio: "Ethan enjoys photography and exploring the world through a lens.",
    headline: "Photographer | Ethan Lewis",
    photo: "https://fakeimg.pl/100x100/?text=Ethan+Lewis",
    interests: ["Photography", "Traveling"],
  },
  {
    id: "id-13",
    name: "Ava Walker",
    bio: "Ava is passionate about AI, programming, and helping others learn new skills.",
    headline: "Tech Educator | Ava Walker",
    photo: "https://fakeimg.pl/100x100/?text=Ava+Walker",
    interests: ["AI", "Education"],
  },
  {
    id: "id-14",
    name: "Lucas Young",
    bio: "Lucas is a passionate coder who loves to learn new programming languages.",
    headline: "Software Developer | Lucas Young",
    photo: "https://fakeimg.pl/100x100/?text=Lucas+Young",
    interests: ["Coding", "Technology"],
  },
  {
    id: "id-15",
    name: "Mia King",
    bio: "Mia loves building apps and exploring new digital tools.",
    headline: "App Developer | Mia King",
    photo: "https://fakeimg.pl/100x100/?text=Mia+King",
    interests: ["App Development", "Coding"],
  },
  {
    id: "id-16",
    name: "Alexander Scott",
    bio: "Alexander is an entrepreneur and digital marketing expert with a passion for technology.",
    headline: "Entrepreneur | Alexander Scott",
    photo: "https://fakeimg.pl/100x100/?text=Alexander+Scott",
    interests: ["Business", "Technology"],
  },
  {
    id: "id-17",
    name: "Liam Perez",
    bio: "Liam is all about building scalable, high-performance web applications.",
    headline: "Full-Stack Developer | Liam Perez",
    photo: "https://fakeimg.pl/100x100/?text=Liam+Perez",
    interests: ["Web Development", "Performance Optimization"],
  },
  {
    id: "id-18",
    name: "Evelyn Harris",
    bio: "Evelyn is a software engineer passionate about solving complex problems.",
    headline: "Software Engineer | Evelyn Harris",
    photo: "https://fakeimg.pl/100x100/?text=Evelyn+Harris",
    interests: ["Engineering", "Problem Solving"],
  },
  {
    id: "id-19",
    name: "Zoe Carter",
    bio: "Creative developer with an eye for design and user experience.",
    headline: "UI/UX Designer | Zoe Carter",
    photo: "https://fakeimg.pl/100x100/?text=Zoe+Carter",
    interests: ["Design", "UX"],
  },
  {
    id: "id-20",
    name: "Benjamin Evans",
    bio: "Benjamin is passionate about web technologies and building modern applications.",
    headline: "Web Developer | Benjamin Evans",
    photo: "https://fakeimg.pl/100x100/?text=Benjamin+Evans",
    interests: ["Web Technologies", "JavaScript"],
  },
  {
    id: "id-21",
    name: "Chloe Mitchell",
    bio: "Chloe is focused on backend development and API design.",
    headline: "Backend Developer | Chloe Mitchell",
    photo: "https://fakeimg.pl/100x100/?text=Chloe+Mitchell",
    interests: ["Backend Development", "APIs"],
  }
]